#!/bin/bash

# Python install
sudo apt-get install -y python3

# Pip install
sudo apt-get install -y python3-pip

# Virutalenv install
sudo pip3 install virtualenv

# apt update
sudo apt-get update && sudo apt-get -y upgrade

# MySql install
sudo apt-get -y install mysql-server

# Mysql config
sudo mysql_secure_installation utility -y

# MySql lib
sudo apt-get install libmysqlclient-dev -y

# Apache install
sudo apt-get install apache2 -y
sudo apt-get install libapache2-mod-wsgi-py3
sudo a2enmod wsgi
sudo apt-get install -y apache2-dev

# Create mysql database
sudo mysql
#sudo mysql -e 'CREATE DATABASE my_application;'
#sudo mysql -e 'CREATE USER `test`@`%` IDENTIFIED BY `zaq1@WSX`;'
#sudo mysql -e 'GRANT ALL PRIVILEGES ON my_application.* TO `test`;'


# Install django inside specific virtualenv
virtualenv I-dom
. I-dom/bin/activate
cd I-dom
git clone -b develop https://github.com/ZarebaMichal/I-dom.git I-DOM
cd I-DOM
pip3 install -r requirements.txt
cd my_application
sudo nano .env
cd ..
python3 manage.py makemigrations
python3 manage.py migrate
python3 manage.py createsuperuser

deactivate

# Apache config
sudo cp /home/ubuntu/I-dom/I-DOM/my_application.conf //etc/apache2/conf-available/my_application.conf
sudo cp /home/ubuntu/I-dom/I-DOM/000-default.conf //etc/apache2/sites-available/000-default.conf
sudo cp /home/ubuntu/I-dom/I-DOM/ports.conf //etc/apache2/ports.conf
sudo a2enconf my_application
sudo service apache2 restart

# Frontend install
sudo apt-get install nodejs -y
sudo apt-get install npm
cd /home/ubuntu/
mkdir Frontend
cd Frontend
git clone https://github.com/adriannajmrocki/idom.git
cd idom
npm install
npm run build



# Nginx install
sudo apt-get install nginx -y
sudo cp /home/ubuntu/I-dom/I-DOM/default //etc/nginx/sites-enabled/default
sudo killall nginx
sudo nginx

