# Generated by Django 3.0.5 on 2020-05-25 22:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('temperature', 'temperature'), ('humidity', 'humidity')], max_length=15)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('notifications', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor_data', models.CharField(max_length=20)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensors')),
            ],
        ),
    ]
