# Generated by Django 3.0.5 on 2020-06-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('temperature', 'temperature'), ('humidity', 'humidity')], max_length=15)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('notifications', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('frequency', models.IntegerField(default=300)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
            },
        ),
        migrations.CreateModel(
            name='SensorsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField(auto_now_add=True)),
                ('sensor_data', models.CharField(max_length=20)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensors')),
            ],
            options={
                'verbose_name': 'Sensor data',
                'verbose_name_plural': 'Sensors data',
            },
        ),
    ]
